### PR TITLE
Several fixes and refactors

### PR DESCRIPTION
**Pull request by GaurangTandon**
throttled the scroll
refactored code
prefixed jquery variables with $

### CODE REVIEW

**Comment by zubairabid** [comment]
Also: what's the utility of the `throttle` function? The scrolling is already throttled, the wrapper doesn't seem to be adding much functionally.

**Comment by GaurangTandon** [comment]
@zubairabid I only noticed that later but that was an automatic eslint change.  I'll check up on it after checking es6 compact for older IE browsers

**Comment by GaurangTandon** [comment]
@zubairabid How was the scrolling already throttled?

**Comment by zubairabid** [comment]
@GaurangTandon There's a scrollHandler with a delay

**Comment by GaurangTandon** [comment]
@zubairabid I missed it, dunno why ._. I have added some more fixes --^

**Comment by GaurangTandon** [comment]
Wrt the latest commit, the idea is that if the materialize file is supposed to provide default values for the page, then it should not be having those !important flags which cannot actually be overridden.

**Comment by GaurangTandon** [comment]
@zubairabid `git rebase master` said branch already uptodate. So I fetched the remote repo, manually resolved a merge conflict, and it seems good now. Please have a look.

**Comment by GaurangTandon** [comment]
By virtue of trying out several Git commands (in no particular order)I found on SO, I have successfully (I think) merged my branch `fixes` on my own fork into this PR. The above six commits are a testament on this webpage for that.

And **this branch also has no conflicts.**

**Pull request merged**
